repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.325
    hooks:
      - id: pyright

# TODO: figure out a way to get this working on github CI :(
#  - repo: local
#    hooks:
#      - id: pytest-check
#        name: pytest-check
#        entry: pytest
#        language: system
#        pass_filenames: false
#        always_run: true
